### ISSUE TITLE
Software Development Tasks

### ISSUE THREAD

**Issue by stratos-karas** [cslab-ntua/HPC-Simulator#6]
A place to write down all the bugs that need to be fixed, the features that need to be added and refactoring ideas.

**Comment by stratos-karas** [comment]
## 4Aug2024

### Bugs
None

### Features
- [ ] Adding new KPIs for better understanding.
- [x] Update API to provide performance counters to simulation.
- [ ] Integrate/Test heatmap inference models.

### Refactoring Ideas
- [x] Generalizing allocation of nodes and cores. Currently the allocation is done exclusively and sequentially.
- [x] Make compute engine and cluster independent.
- [ ] Make logging and plotting independent.
- [x] Move as much plotting as possible to the frontend.
- [ ] Make experiments' results shareable.
- [ ] Realistic take on scheduling decision making. Create a context for scheduling that is found in real HPC systems.
- [x] Adding users.

**Comment by nikosT** [comment]
@stratos-karas do we need this?

**Comment by stratos-karas** [comment]
We can move the unchecked to a new features release list.
